on:
  push:
    branches:
      - main

name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11.0.16
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.16

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        env:
          kakao.client.id: ${{SECRETS.KAKAO_CLIENT_ID}}
          kakao.redirect.url: ${{SECRETS.KAKAO_REDIRECT_URL}}
          google.client.id: ${{SECRETS.GOOGLE_CLIENT_ID}}
          google.client.pw: ${{SECRETS.GOOGLE_CLIENT_PW}}
          google.redirect.url: ${{SECRETS.GOOGLE_REDIRECT_URL}}
          spring.mail.username: ${{SECRETS.MAIL_USERNAME}}
          spring.mail.password: ${{SECRETS.MAIL_PASSWORD}}
          jwt.secret: ${{SECRETS.JWT_SECRET}}
          
