on:
  push:
    branches:
      - main

name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11.0.16
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.16

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        env:
          kakao.client.id: ${{SECRETS.KAKAO_CLIENT_ID}}
          kakao.redirect.url: ${{SECRETS.KAKAO_REDIRECT_URL}}
          google.client.id: ${{SECRETS.GOOGLE_CLIENT_ID}}
          google.client.pw: ${{SECRETS.GOOGLE_CLIENT_PW}}
          google.redirect.url: ${{SECRETS.GOOGLE_REDIRECT_URL}}
          spring.mail.username: ${{SECRETS.MAIL_USERNAME}}
          spring.mail.password: ${{SECRETS.MAIL_PASSWORD}}
          jwt.secret: ${{SECRETS.JWT_SECRET}}
          
      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          aws-access-key-id: ${{SECRETS.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{SECRETS.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://magorosc/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name testapp --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=magorosc,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip

          
